name = "TeamInfo Share"
uid = "teaminfo-share-v10"
version = 10
copyright = ""
description = [[Shares data in team about nukes, smds and exps completions
requires UI mod tools]]
author = "4z0t"
url = ""
icon = "/mods/TIS/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
__umt = true
