name = "Better Colors"
version = 1
copyright = ""
description = ""
author = "4z0t"
url = ""
uid = "better-colors-v01"
--icon = "/mods/BetterColors/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
