name = "Engineer Alt Selection"
version = 1
copyright = ""
description = ""
author = "4z0t"
url = ""
uid = "engineer-alt-selection-v01"
icon = "/mods/EAS/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
