layout = {
	['l_factory'] = {left = 196, top = 142, width = 56, height = 40, leftOffset = 0, topOffset = 0, },
	['l_factory-icons'] = {left = 42, top = 66, width = 130, height = 120, leftOffset = 0, topOffset = 0, },
	['avatar-s-e-f_bmp'] = {left = 38, top = 55, width = 52, height = 52, leftOffset = 1, topOffset = 1, },
	['strat-icon-sea_bmp'] = {left = 150, top = 50, width = 8, height = 8, leftOffset = 0, topOffset = 1, },
	['strat-icon-air_bmp'] = {left = 105, top = 49, width = 8, height = 8, leftOffset = 0, topOffset = 0, },
	['strat-icon-land_bmp'] = {left = 61, top = 49, width = 8, height = 8, leftOffset = 0, topOffset = 0, },
	['tech-3_bmp'] = {left = 16, top = 64, width = 28, height = 28, leftOffset = 1, topOffset = 0, },
	['tech-2_bmp'] = {left = 16, top = 105, width = 28, height = 28, leftOffset = 1, topOffset = 0, },
	['tech-1_bmp'] = {left = 16, top = 147, width = 28, height = 28, leftOffset = 1, topOffset = 0, },
	['bracket_bmp'] = {left = 177, top = 145, width = 28, height = 48, leftOffset = 1, topOffset = 1, },
	['factory-panel_brd_lr'] = {left = 128, top = 145, width = 60, height = 52, leftOffset = 1, topOffset = 0, },
	['factory-panel_brd_lm'] = {left = 84, top = 145, width = 44, height = 48, leftOffset = 0, topOffset = 0, },
	['factory-panel_brd_ll'] = {left = 6, top = 145, width = 36, height = 52, leftOffset = 1, topOffset = 0, },
	['factory-panel_brd_vert_r'] = {left = 128, top = 101, width = 60, height = 44, leftOffset = 1, topOffset = 0, },
	['factory-panel_brd_vert_l'] = {left = 6, top = 101, width = 36, height = 44, leftOffset = 1, topOffset = 0, },
	['factory-panel_brd_ur'] = {left = 128, top = 41, width = 60, height = 16, leftOffset = 1, topOffset = 0, },
	['factory-panel_brd_horz_um'] = {left = 84, top = 45, width = 44, height = 12, leftOffset = 0, topOffset = 0, },
	['factory-panel_brd_ul'] = {left = 6, top = 41, width = 36, height = 16, leftOffset = 1, topOffset = 0, },
	['factory-panel_bmp'] = {left = 4, top = 39, width = 184, height = 160, leftOffset = 0, topOffset = 0, },
}
