layout = {
	['l_mass-numbers'] = {left = 226, top = 12, width = 60, height = 25, leftOffset = 0, topOffset = 0, },
	['l_energy-numbers'] = {left = 226, top = 43, width = 61, height = 21, leftOffset = 0, topOffset = 0, },
	['l_energy-bar'] = {left = 74, top = 40, width = 150, height = 18, leftOffset = 0, topOffset = 0, },
	['l_mass-bar'] = {left = 74, top = 12, width = 150, height = 18, leftOffset = 0, topOffset = 0, },
	['alert-caution_bmp'] = {left = 37, top = 33, width = 48, height = 44, leftOffset = 0, topOffset = 0, },
	['alert-no-parking_bmp'] = {left = 36, top = 1, width = 52, height = 52, leftOffset = 1, topOffset = 1, },
	['alert-icon_bmp'] = {left = 48, top = 8, width = 28, height = 36, leftOffset = 1, topOffset = 0, },
	['l_mass-bar-numbers'] = {left = 78, top = 24, width = 111, height = 19, leftOffset = 0, topOffset = 0, },
	['l_energy-bar-numbers'] = {left = 11, top = 32, width = 141, height = 33, leftOffset = 0, topOffset = 0, },
	['l_mass-icon'] = {left = 43, top = 9, width = 36, height = 36, leftOffset = 0, topOffset = 0, },
	['l_energy-icon'] = {left = 43, top = 36, width = 36, height = 36, leftOffset = 0, topOffset = 0, },
	['l_tab'] = {left = 21, top = 29, width = 12, height = 22, leftOffset = 0, topOffset = 0, },
	['caution-energy-panel_bmp'] = {left = 31, top = 39, width = 316, height = 32, leftOffset = 0, topOffset = 0, },
	['caution-mass-panel_bmp'] = {left = 32, top = 9, width = 316, height = 32, leftOffset = 1, topOffset = 0, },
	['alert-energy-panel_bmp'] = {left = 31, top = 39, width = 316, height = 32, leftOffset = 0, topOffset = 0, },
	['alert-mass-panel_bmp'] = {left = 32, top = 9, width = 316, height = 32, leftOffset = 1, topOffset = 0, },
	['bracket-right_bmp'] = {left = 336, top = 5, width = 24, height = 68, leftOffset = 0, topOffset = 0, },
	['bracket-left_bmp'] = {left = 17, top = 5, width = 24, height = 68, leftOffset = 0, topOffset = 0, },
	['bracket-energy-r_bmp'] = {left = 330, top = 4, width = 20, height = 72, leftOffset = 0, topOffset = 0, },
	['bracket-energy-l_bmp'] = {left = 27, top = 5, width = 24, height = 72, leftOffset = 1, topOffset = 1, },
	['resources_panel_bmp'] = {left = 27, top = 6, width = 324, height = 72, leftOffset = 0, topOffset = 1, },
}
