name = "Move only"
version = 1
copyright = ""
description = ""
author = "4z0t"
url = ""
uid = "move-only-v01"
icon = "/mods/Move/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
