-- local ModifyBuildables = import('/lua/ui/notify/enhancementqueue.lua').ModifyBuildablesForACU
-- local selection = GetSelectedUnits()
-- local availableOrders, availableToggles, buildableCategories = GetUnitCommandData(selection)
-- local newBuildableCategories = ModifyBuildables(buildableCategories, selection)
-- local buildable = EntityCategoryGetUnitList(buildableCategories)
-- LOG(repr(buildable))
