name = "ReUI.UI.Controls"
uid = "reui-ui-controls-1.0.0"
version = 1
copyright = ""
description = [[]]
author = "4z0t"
icon = "/mods/ReUI.UI.Controls/icon.png"
url = ""
selectable = false
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}

ReUI = 'ReUI.UI.Controls=1.0.0'
