layout = {
	['end_on'] = {left = 19, top = 2, width = 25, height = 14, },
	['end_off'] = {left = 19, top = 2, width = 25, height = 14, },
	['down_on'] = {left = 19, top = 4, width = 25, height = 12, },
	['down_off'] = {left = 19, top = 4, width = 25, height = 12, },
	['up_on'] = {left = 19, top = 3, width = 25, height = 13, },
	['up_off'] = {left = 19, top = 3, width = 25, height = 13, },
	['home_on'] = {left = 20, top = 1, width = 24, height = 15, },
	['home_off'] = {left = 20, top = 1, width = 24, height = 15, },
	['top_btn_over'] = {left = 0, top = 0, width = 60, height = 16, },
	['top_btn_up'] = {left = 0, top = 0, width = 60, height = 16, },
	['top_btn_dis'] = {left = 1, top = 0, width = 59, height = 16, },
	['mid_btn_over'] = {left = 0, top = 0, width = 60, height = 16, },
	['mid_btn_up'] = {left = 0, top = 0, width = 60, height = 16, },
	['mid_btn_dis'] = {left = 1, top = 0, width = 59, height = 16, },
	['bottom_btn_over'] = {left = 0, top = 0, width = 60, height = 16, },
	['bottom_btn_up'] = {left = 0, top = 0, width = 60, height = 16, },
	['bottom_btn_dis'] = {left = 1, top = 0, width = 59, height = 16, },
}
