name = "Factory Templates"
version = 1
copyright = ""
description = [[]]
author = "4z0t"
url = ""
uid = "factory-templates-v01"
exclusive = false
ui_only = true
conflicts = {}
AGP = "FactoryTemplatesHandler"
