layout = {
	['fforward_on'] = {left = 6, top = 14, width = 16, height = 29, },
	['fforward_off'] = {left = 6, top = 14, width = 16, height = 29, },
	['forward_on'] = {left = 7, top = 13, width = 13, height = 30, },
	['forward_off'] = {left = 7, top = 13, width = 13, height = 30, },
	['back_on'] = {left = 6, top = 13, width = 13, height = 30, },
	['back_off'] = {left = 6, top = 13, width = 13, height = 30, },
	['rewind_on'] = {left = 6, top = 13, width = 16, height = 29, },
	['rewind_off'] = {left = 6, top = 13, width = 16, height = 29, },
	['template_on'] = {left = 6, top = 18, width = 16, height = 19, },
	['template_off'] = {left = 6, top = 18, width = 16, height = 19, },
	['infinite_on'] = {left = 5, top = 16, width = 19, height = 23, },
	['infinite_off'] = {left = 5, top = 16, width = 19, height = 23, },
	['pause_on'] = {left = 5, top = 17, width = 18, height = 18, },
	['pause_off'] = {left = 5, top = 17, width = 18, height = 18, },
	['mid_btn_selected'] = {left = 0, top = 0, width = 24, height = 52, },
	['mid_btn_over'] = {left = 0, top = 0, width = 24, height = 52, },
	['mid_btn_up'] = {left = 0, top = 0, width = 24, height = 52, },
	['mid_btn_dis'] = {left = 0, top = 0, width = 24, height = 52, },
	['right_btn_over'] = {left = 0, top = 0, width = 24, height = 52, },
	['right_btn_up'] = {left = 0, top = 0, width = 24, height = 52, },
	['right_btn_dis'] = {left = 1, top = 0, width = 23, height = 52, },
	['left_btn_over'] = {left = 0, top = 0, width = 24, height = 52, },
	['left_btn_up'] = {left = 0, top = 0, width = 24, height = 52, },
	['left_btn_dis'] = {left = 0, top = 0, width = 24, height = 52, },
}
