name = "ReUI.Core.Events"
uid = "reui-core-events-1.0.0"
version = 1
copyright = ""
description = [[]]
author = "4z0t"
icon = "/mods/ReUI.Core.Events/icon.png"
url = ""
selectable = false
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}

ReUI = 'ReUI.Core.Events=1.0.0'
