name = "Specific Target Priorities"
version = 2
uid = "Specific-Target-Priorities-v02"
copyright = ""
description = "Hover over specific unit to target its type"
author = "4z0t"
url = ""
exclusive = false
ui_only = true
conflicts = {}
