name = "Smart Ring Display"
uid = "smart-ring-display-v01"
version = 1
copyright = ""
description = [[Shows ranges of weapons of units when hover over and press shift]]
author = "4z0t"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
