name = "Advanced Key Actions"
version = 1
copyright = "MIT License"
description = [[]]
author = "4z0t"
url = "https://github.com/4z0t/FAF-UI-Mods"
uid = "advanced-key-actions-v01"
exclusive = false
ui_only = true
conflicts = {}
__umt = true
