name = "ReUI.Hotbuild"
uid = "reui-Hotbuild-1.1.0"
version = 1
copyright = ""
description = [[]]
author = "4z0t"
icon = "/mods/ReUI.Hotbuild/icon.png"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}

ReUI = 'ReUI.Hotbuild=1.1.0'
