name = "FilterSelection"
uid = "a91e97de-51e2-11eb-ae93-0242ac130006"
version = 1.0
copyright = ""
description = "Mod provides creating keybinds on unit filters, that selects all units of the same blueprint on screen on call. F1 for binding."
author = "4z0t"
url = ""
icon = '/mods/FilterSelection/icon.jpg'
enabled = true
exclusive = false
ui_only = true
conflicts = {}
__umt = true