name = "Group Split"
version = 1
copyright = ""
description = ""
author = "4z0t"
url = ""
uid = "group-split-v01"
icon = "/mods/GS/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
