name = "ReUI.Economy"
uid = "reui-economy-1.3.0"
version = 3
copyright = ""
description = [[]]
author = "4z0t"
icon = "/mods/ReUI.Economy/icon.png"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}

ReUI = 'ReUI.Economy=1.3.0'
