name = "HotBuild Overhaul"
uid = "hotbuild-overhaul-4z0t-v01"
version = 1
copyright = ""
description = [[]]
author = "4z0t"
url = ""
icon = "/mods/HBO/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {"ui-mod-tools-4z0t-v02"}
requiresNames = {}
conflicts = {}
after = {}
