layout = {
	['default_btn_down'] = {left = 0, top = 0, width = 24, height = 24, },
	['default_btn_over'] = {left = 0, top = 0, width = 23, height = 22, },
	['default_btn_up'] = {left = 0, top = 0, width = 22, height = 22, },
	['default_btn_dis'] = {left = 0, top = 0, width = 22, height = 22, },
	['pinned_btn_down'] = {left = 0, top = 0, width = 24, height = 24, },
	['pinned_btn_over'] = {left = 1, top = 1, width = 22, height = 22, },
	['pinned_btn_up'] = {left = 4, top = 2, width = 17, height = 21, },
	['pinned_btn_dis'] = {left = 4, top = 2, width = 17, height = 21, },
	['pin_btn_down'] = {left = 0, top = 0, width = 24, height = 24, },
	['pin_btn_over'] = {left = 1, top = 1, width = 22, height = 21, },
	['pin_btn_up'] = {left = 3, top = 2, width = 17, height = 20, },
	['pin_btn_dis'] = {left = 3, top = 2, width = 17, height = 20, },
	['config_btn_down'] = {left = 0, top = 0, width = 24, height = 24, },
	['config_btn_over'] = {left = 1, top = 1, width = 22, height = 21, },
	['config_btn_up'] = {left = 3, top = 2, width = 20, height = 20, },
	['config_btn_dis'] = {left = 3, top = 2, width = 20, height = 20, },
	['close_btn_down'] = {left = 0, top = 0, width = 24, height = 24, },
	['close_btn_over'] = {left = 1, top = 1, width = 22, height = 21, },
	['close_btn_up'] = {left = 0, top = 0, width = 24, height = 23, },
	['close_btn_dis'] = {left = 3, top = 4, width = 18, height = 16, },
}
