name = "KeyBinds Overhaul"
uid = "keybinds-overhaul-4z0t-v01"
version = 1
copyright = ""
description = [[]]
author = "4z0t"
url = ""
icon = "/mods/KBO/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requiresNames = {}
conflicts = {}
after = {}
