name = "your mod name"
version = 1
copyright = ""
description = "your description"
author = "you"
url = ""
uid = "your-mod-uid"
icon = "/mods/Pattern/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
