layout = {
	['drag-handle-ur_btn_down'] = {left = 0, top = 0, width = 69, height = 92, },
	['drag-handle-ur_btn_over'] = {left = 0, top = 0, width = 65, height = 88, },
	['drag-handle-ur_btn_up'] = {left = 0, top = 0, width = 65, height = 88, },
	['drag-handle-ur_btn_dis'] = {left = 0, top = 0, width = 65, height = 88, },
	['drag-handle-ul_btn_down'] = {left = 13, top = 0, width = 67, height = 92, },
	['drag-handle-ul_btn_over'] = {left = 17, top = 0, width = 63, height = 88, },
	['drag-handle-ul_btn_up'] = {left = 17, top = 0, width = 63, height = 88, },
	['drag-handle-ul_btn_dis'] = {left = 17, top = 0, width = 63, height = 88, },
	['drag-handle-ll_btn_down'] = {left = 13, top = 4, width = 67, height = 92, },
	['drag-handle-ll_btn_over'] = {left = 17, top = 8, width = 63, height = 88, },
	['drag-handle-ll_btn_up'] = {left = 17, top = 8, width = 63, height = 88, },
	['drag-handle-ll_btn_dis'] = {left = 17, top = 8, width = 63, height = 88, },
	['drag-handle-lr_btn_down'] = {left = 0, top = 4, width = 68, height = 92, },
	['drag-handle-lr_btn_over'] = {left = 0, top = 8, width = 64, height = 88, },
	['drag-handle-lr_btn_up'] = {left = 0, top = 8, width = 64, height = 88, },
	['drag-handle-lr_btn_dis'] = {left = 0, top = 8, width = 64, height = 88, },
}
